import Head from "next/head";
import Image from "next/image";
import Paragraph from "../components/UI/Paragraph";
import Subtitle from "../components/UI/Subtitle";
import Title from "../components/UI/Title";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Landing-1</title>
        <meta name="description" content="Generated by Nevyl" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.menu}>
        <div className={styles.menu_logo}>
          <Image src="/img/img1.png" alt="Logo" width={352} height={177} />
        </div>
        <div className={styles.btn}>
          <a href="#" rel="nofollow">
            <span>DOWNLOAD APP ICON</span>
          </a>
        </div>
      </div>
      <main className={styles.main}>
        <header className={styles.section_flex}>
          <div className={styles.section_1}>
            <div className={styles.subsec_1_flex}>
              <div className={styles.logo}>
                <Image
                  src="/img/img1.png"
                  alt="Logo"
                  width={352}
                  height={177}
                />
              </div>
              <div className={styles.tittle}>
                <Title size="small" color="black">
                  Get paid to treat your child´s anxiety and depression
                  symptoms!
                </Title>
              </div>
            </div>
            <div className={styles.text}>
              <Paragraph color="black">
                Get your child’s symptoms virtually treated by Dr. MOOVES
                <br /> app and <b>get paid!</b>
              </Paragraph>
              <Subtitle color="black">
                Receive checks from your insurance company by treating your
                children’s A&D symptoms.
              </Subtitle>
              <Title size="small" color="black">
                How does it work?
              </Title>
              <ul>
                <li>
                  Dr. Mooves app is a fun dance virtual therapy, which records
                  their stability, sway, basal support, symmetry, synchrony and
                  much more.
                </li>
                <li>
                  After performing every dance, children get a different
                  prescription dance and a change in their improvement
                  potential. The more progress your child shows, the better
                  compensation you will receive from your insurance company.
                </li>
                <li>
                  All dances grow their mental strength and cognitive resiliency
                  helping with anxiety and depression symptoms
                </li>
              </ul>
              <Subtitle color="black">
                Be compensated for your child’s health!
              </Subtitle>
            </div>
            <div className={styles.btn}>
              <a href="#" rel="nofollow">
                DOWNLOAD APP ICON
              </a>
            </div>
          </div>
          <div className={styles.section_2}>
            <div className={styles.video}>
              <div>
                <video width="100%" controls>
                  <source src="/img/mov_bbb.mp4" type="video/mp4" />
                  Your browser does not support HTML video.
                </video>
              </div>
            </div>
          </div>
        </header>
      </main>

      <footer className={styles.footer}>
        <a href="" target="_blank" rel="noopener noreferrer"></a>
      </footer>
    </div>
  );
}
