import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import React from "react";
import YouTube from "react-youtube";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Landing1</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.menu}>
        <div className={styles.menu_logo}>
          <Image src="/img/img1.png" alt="Logo" width={352} height={177} />
        </div>
        <div class={styles.btn}>
          <a href="#" rel="nofollow">
            <span>DOWNLOAD APP ICON</span>
          </a>
        </div>
      </div>
      <main className={styles.main}>
        <header className={styles.section_flex}>
          <div className={styles.section_1}>
            <div className={styles.logo}>
              <Image src="/img/img1.png" alt="Logo" width={352} height={177} />
            </div>
            <div className={styles.tittle}>
              <h1>
                Get paid to treat your child´s anxiety and depression symptoms!
              </h1>
            </div>
            <p>
              Get your child’s symptoms virtually treated by Dr. MOOVES
              <br /> app and <b>get paid!</b>
            </p>
            <h3>
              Receive checks from your insurance company by treating your
              children’s A&D symptoms.
            </h3>
            <h3>How does it work?</h3>
            <p>
              Dr. Mooves app is a fun dance virtual therapy, which records their
              stability, sway, basal support, symmetry, synchrony and much more.
            </p>
            <p>
              After performing every dance, children get a different
              prescription dance and a change in their improvement potential.
              The more progress your child shows, the better compensation you
              will receive from your insurance company.
            </p>
            <p>
              All dances grow their mental strength and cognitive resiliency
              helping with anxiety and depression symptoms
            </p>
            <h2>Be compensated for your child’s health!</h2>
          </div>
          <div className={styles.section_2}>
            <div class={styles.btn}>
              <a href="#" rel="nofollow">
                <span>DOWNLOAD APP ICON</span>
              </a>
            </div>
            <div className={styles.video}>
              <div>
                <video width="80%" controls>
                  <source src="/img/mov_bbb.mp4" type="video/mp4" />
                  Your browser does not support HTML video.
                </video>
              </div>
            </div>
          </div>
        </header>
      </main>

      <footer className={styles.footer}>
        <a href="" target="_blank" rel="noopener noreferrer"></a>
      </footer>
    </div>
  );
}
